#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
tint2 &
# numlockx &
xsetroot -cursor_name left_ptr &
picom &
xwallpaper --output eDP-1 --zoom Images/2021-03-17_01-14-26.png &
xset -dpms &&
xset s off &

bspc monitor -d  1 2 3 4 5 6 7 8 9 10
bspc config border_width         5
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config normal_border_color         "#7d7d7d"
bspc config active_border_color         "#4ca4fc"
bspc config focused_border_color        "#EBEBEB"

#bspc rule -a Firefox desktop='^2'

bspc rule -a Screenkey manage=off
bspc rule Tint2 layer=normal
